# Generated by Django 4.2.2 on 2023-06-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userloginhistory",
            name="last_logout_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
